addSbtPlugin("com.eed3si9n"                % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("org.typelevel"               % "sbt-tpolecat"  % "0.5.2")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"  % "2.3.1")
addSbtPlugin("com.github.sbt"              % "sbt-dynver"    % "5.1.1")
addSbtPlugin("com.indoorvivants.snapshots" % "sbt-snapshots" % "0.0.11")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"  % "2.5.6")
addSbtPlugin("com.github.sbt"              % "sbt-header"    % "5.11.0")
