addSbtPlugin("com.eed3si9n"                % "sbt-buildinfo" % "0.12.0")
addSbtPlugin("org.typelevel"               % "sbt-tpolecat"  % "0.5.2")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"  % "2.2.0")
addSbtPlugin("com.github.sbt"              % "sbt-dynver"    % "5.0.1")
addSbtPlugin("com.indoorvivants.snapshots" % "sbt-snapshots" % "0.0.7")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("de.heikoseeberger"           % "sbt-header"    % "5.10.0")
